name = "hospital-fee-calc"
compatibility_date = "2026-05-03"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "search-analytics-db"
database_id = "1db70fcf-0e42-4fa3-af1c-52ef45619dba"
